function Gmenu

%Autor: Alejandro Hidalgo - Felipe Santibañez
%Estudiante de Electrónica
%***************************************************************
% GMenu: programilla
%***************************************************************
clear,clc,cla,close all
%Creamos figura
figdiag=figure('Units','Centimeters',...
    'Position',[1 1 25 18],... %Tamaño de la presentación
    'Number','off',...
    'Name','Proyecto: Escritor laborioso', ...
    'Menubar','none', ...
    'color',[0 0 1.0]);
%Ubicamos ejes en figura
axes('Units','Normalized',...
'Position',[0 0 1 1]);
%Incluir imagen
%Importamos imagen *.jpg,junto con su mapa de colores
[x,map]=imread('robot.jpg','jpg');
%Representamos imagen en figura, con su mapa de colores
image(x),colormap(map),axis off,hold on

%-----------------Títulos sobre imagen----------------------

%Título
text(27,75,'Presentacion Proyecto Final',...
    'Fontname','Arial','Fontsize',25,'Fontangle','Italic', ...
    'Fontweight','Bold','color',[0.1 0.4 0.6]);
%Nombres de programadores
text(415,450,'Integrantes: Alejandro Hidalgo','Fontname', ...
'Comic Sans MS','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',20,'color',[0.3 0.5 0.7]);
text(573,495,'Felipe Santibañez','Fontname', ...
'Comic Sans MS','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',20,'color',[0.3 0.5 0.7]);



%--------------------------Botón Continuar-----------------

%home

botok=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.60 .19 .12 .05], ...
'String','HOME',...
'Callback','clear all;clc;Hogar;'); 

%Problema directo
botok=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.60 .12 .12 .05], ...
'String','P_Directo',...
'Callback','clear all; close all;clc; Gpdirecto;'); 

%Problema inverso
botok=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.60 .05 .12 .05], ...
'String','P_Inverso',...
'Callback','clear all; close all;clc; Gpinverso;'); 


%Aprender Largo
botok=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.84 .19 .12 .05], ...
'String','ENTRENAR_normal',...
'Callback','clear all; close all;clc; GpEntrenarNormal;'); 

%Aprender Recursivo
botok=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.84 .12 .12 .05], ...
'String','Entrenar_X',...
'Callback','clear all; close all;clc; GpEntrenarAutomatico;'); 


% Escrtitor
botok=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.84 .05 .12 .05], ...
'String','ESCRITOR',...
'Callback','clear all; close all;clc; GpEscritor;'); 




